### ISSUE TITLE
flow control: conditional jump/skip in pipeline

### ISSUE THREAD

**Issue by debugloop** [bwNetFlow/flowpipeline#9]
This should implementable but hard to put into an accessible and idiomatic syntax or segment structure. Some ideas:

```yaml
- segment: skip # skip next segment if condition is met
  config:
    condition: '<flowfilter syntax>'
    jump: 1 # default, how many segments to jump over
    skip-if: true # default, can be used to make `skip` behave as an `if` statement... maybe name this `invert`?
```

```yaml
- segment: sample # do every n flows only
  config:
    flows: 100
    jump: 1 # default
    condition: '<flowfilter syntax>'
```

Is having a condition in here a good idea? `skip` with `jump: 2` and then `sample` with `jump: 1` would be equivalent. but harder to write.
